name: API CD - Docker Image Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ecomacrrahul96

      - name: Build Docker Image
        run: |
          docker build -t ecomacrrahul96.azurecr.io/ecomapi:${{ github.sha }} -t ecomacrrahul96.azurecr.io/ecomapi:latest -f Dockerfile .

      - name: Push to ACR
        run: |
          docker push ecomacrrahul96.azurecr.io/ecomapi:${{ github.sha }}
          docker push ecomacrrahul96.azurecr.io/ecomapi:latest

      - name: Deploy Image to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ecom-api-rahul96
          images: ecomacrrahul96.azurecr.io/ecomapi:${{ github.sha }}
