name: API CD - Deploy to Azure (OIDC)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }

      - run: dotnet restore EcomAPI/EcomAPI.csproj
      - run: dotnet build EcomAPI/EcomAPI.csproj --no-restore -c Release
      - run: dotnet test EcomAPI.Tests/EcomAPI.Tests.csproj --no-build -c Release || echo "No tests or tests failed but continue"
      - run: dotnet publish EcomAPI/EcomAPI.csproj -c Release -o ${{ github.workspace }}/publish

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ecom-api-rahul96
          package: ${{ github.workspace }}/publish
